// Départements de France métropolitaine et leur zone climatique (H1 / H2 / H3),
// telle qu'utilisée par la réglementation thermique et les fiches CEE.
// [code, nom, région, zone]
const RAW = [
  ['01', 'Ain', 'Auvergne-Rhône-Alpes', 'H1'],
  ['02', 'Aisne', 'Hauts-de-France', 'H1'],
  ['03', 'Allier', 'Auvergne-Rhône-Alpes', 'H1'],
  ['04', 'Alpes-de-Haute-Provence', "Provence-Alpes-Côte d'Azur", 'H2'],
  ['05', 'Hautes-Alpes', "Provence-Alpes-Côte d'Azur", 'H1'],
  ['06', 'Alpes-Maritimes', "Provence-Alpes-Côte d'Azur", 'H3'],
  ['07', 'Ardèche', 'Auvergne-Rhône-Alpes', 'H2'],
  ['08', 'Ardennes', 'Grand Est', 'H1'],
  ['09', 'Ariège', 'Occitanie', 'H2'],
  ['10', 'Aube', 'Grand Est', 'H1'],
  ['11', 'Aude', 'Occitanie', 'H3'],
  ['12', 'Aveyron', 'Occitanie', 'H2'],
  ['13', 'Bouches-du-Rhône', "Provence-Alpes-Côte d'Azur", 'H3'],
  ['14', 'Calvados', 'Normandie', 'H1'],
  ['15', 'Cantal', 'Auvergne-Rhône-Alpes', 'H1'],
  ['16', 'Charente', 'Nouvelle-Aquitaine', 'H2'],
  ['17', 'Charente-Maritime', 'Nouvelle-Aquitaine', 'H2'],
  ['18', 'Cher', 'Centre-Val de Loire', 'H2'],
  ['19', 'Corrèze', 'Nouvelle-Aquitaine', 'H1'],
  ['2A', 'Corse-du-Sud', 'Corse', 'H3'],
  ['2B', 'Haute-Corse', 'Corse', 'H3'],
  ['21', "Côte-d'Or", 'Bourgogne-Franche-Comté', 'H1'],
  ['22', "Côtes-d'Armor", 'Bretagne', 'H2'],
  ['23', 'Creuse', 'Nouvelle-Aquitaine', 'H1'],
  ['24', 'Dordogne', 'Nouvelle-Aquitaine', 'H2'],
  ['25', 'Doubs', 'Bourgogne-Franche-Comté', 'H1'],
  ['26', 'Drôme', 'Auvergne-Rhône-Alpes', 'H2'],
  ['27', 'Eure', 'Normandie', 'H1'],
  ['28', 'Eure-et-Loir', 'Centre-Val de Loire', 'H1'],
  ['29', 'Finistère', 'Bretagne', 'H2'],
  ['30', 'Gard', 'Occitanie', 'H3'],
  ['31', 'Haute-Garonne', 'Occitanie', 'H2'],
  ['32', 'Gers', 'Occitanie', 'H2'],
  ['33', 'Gironde', 'Nouvelle-Aquitaine', 'H2'],
  ['34', 'Hérault', 'Occitanie', 'H3'],
  ['35', 'Ille-et-Vilaine', 'Bretagne', 'H2'],
  ['36', 'Indre', 'Centre-Val de Loire', 'H2'],
  ['37', 'Indre-et-Loire', 'Centre-Val de Loire', 'H2'],
  ['38', 'Isère', 'Auvergne-Rhône-Alpes', 'H1'],
  ['39', 'Jura', 'Bourgogne-Franche-Comté', 'H1'],
  ['40', 'Landes', 'Nouvelle-Aquitaine', 'H2'],
  ['41', 'Loir-et-Cher', 'Centre-Val de Loire', 'H2'],
  ['42', 'Loire', 'Auvergne-Rhône-Alpes', 'H1'],
  ['43', 'Haute-Loire', 'Auvergne-Rhône-Alpes', 'H1'],
  ['44', 'Loire-Atlantique', 'Pays de la Loire', 'H2'],
  ['45', 'Loiret', 'Centre-Val de Loire', 'H1'],
  ['46', 'Lot', 'Occitanie', 'H2'],
  ['47', 'Lot-et-Garonne', 'Nouvelle-Aquitaine', 'H2'],
  ['48', 'Lozère', 'Occitanie', 'H2'],
  ['49', 'Maine-et-Loire', 'Pays de la Loire', 'H2'],
  ['50', 'Manche', 'Normandie', 'H2'],
  ['51', 'Marne', 'Grand Est', 'H1'],
  ['52', 'Haute-Marne', 'Grand Est', 'H1'],
  ['53', 'Mayenne', 'Pays de la Loire', 'H2'],
  ['54', 'Meurthe-et-Moselle', 'Grand Est', 'H1'],
  ['55', 'Meuse', 'Grand Est', 'H1'],
  ['56', 'Morbihan', 'Bretagne', 'H2'],
  ['57', 'Moselle', 'Grand Est', 'H1'],
  ['58', 'Nièvre', 'Bourgogne-Franche-Comté', 'H1'],
  ['59', 'Nord', 'Hauts-de-France', 'H1'],
  ['60', 'Oise', 'Hauts-de-France', 'H1'],
  ['61', 'Orne', 'Normandie', 'H1'],
  ['62', 'Pas-de-Calais', 'Hauts-de-France', 'H1'],
  ['63', 'Puy-de-Dôme', 'Auvergne-Rhône-Alpes', 'H1'],
  ['64', 'Pyrénées-Atlantiques', 'Nouvelle-Aquitaine', 'H2'],
  ['65', 'Hautes-Pyrénées', 'Occitanie', 'H2'],
  ['66', 'Pyrénées-Orientales', 'Occitanie', 'H3'],
  ['67', 'Bas-Rhin', 'Grand Est', 'H1'],
  ['68', 'Haut-Rhin', 'Grand Est', 'H1'],
  ['69', 'Rhône', 'Auvergne-Rhône-Alpes', 'H1'],
  ['70', 'Haute-Saône', 'Bourgogne-Franche-Comté', 'H1'],
  ['71', 'Saône-et-Loire', 'Bourgogne-Franche-Comté', 'H1'],
  ['72', 'Sarthe', 'Pays de la Loire', 'H2'],
  ['73', 'Savoie', 'Auvergne-Rhône-Alpes', 'H1'],
  ['74', 'Haute-Savoie', 'Auvergne-Rhône-Alpes', 'H1'],
  ['75', 'Paris', 'Île-de-France', 'H1'],
  ['76', 'Seine-Maritime', 'Normandie', 'H1'],
  ['77', 'Seine-et-Marne', 'Île-de-France', 'H1'],
  ['78', 'Yvelines', 'Île-de-France', 'H1'],
  ['79', 'Deux-Sèvres', 'Nouvelle-Aquitaine', 'H2'],
  ['80', 'Somme', 'Hauts-de-France', 'H1'],
  ['81', 'Tarn', 'Occitanie', 'H2'],
  ['82', 'Tarn-et-Garonne', 'Occitanie', 'H2'],
  ['83', 'Var', "Provence-Alpes-Côte d'Azur", 'H3'],
  ['84', 'Vaucluse', "Provence-Alpes-Côte d'Azur", 'H2'],
  ['85', 'Vendée', 'Pays de la Loire', 'H2'],
  ['86', 'Vienne', 'Nouvelle-Aquitaine', 'H2'],
  ['87', 'Haute-Vienne', 'Nouvelle-Aquitaine', 'H1'],
  ['88', 'Vosges', 'Grand Est', 'H1'],
  ['89', 'Yonne', 'Bourgogne-Franche-Comté', 'H1'],
  ['90', 'Territoire de Belfort', 'Bourgogne-Franche-Comté', 'H1'],
  ['91', 'Essonne', 'Île-de-France', 'H1'],
  ['92', 'Hauts-de-Seine', 'Île-de-France', 'H1'],
  ['93', 'Seine-Saint-Denis', 'Île-de-France', 'H1'],
  ['94', 'Val-de-Marne', 'Île-de-France', 'H1'],
  ['95', "Val-d'Oise", 'Île-de-France', 'H1'],
]

export const DEPARTMENTS = Object.fromEntries(
  RAW.map(([code, name, region, zone]) => [code, { code, name, region, zone }]),
)

export const DEPARTMENT_LIST = RAW.map(([code, name]) => ({ code, name }))
